create table country (code varchar(64) not null, country_name varchar(64) not null, primary key(code)) default character set utf8 collate utf8_unicode_ci engine = innodb;
insert into country (code, country_name) values ('AF', 'Afghanistan');
insert into country (code, country_name) values ('AX', 'Åland Islands');
Insert Into country (code, country_name) Values ('AL', 'Albania');
Insert Into country (code, country_name) Values ('DZ', 'Algeria');
Insert Into country (code, country_name) Values ('AS', 'American Samoa');
Insert Into country (code, country_name) Values ('AD', 'Andorra');
Insert Into country (code, country_name) Values ('AO', 'Angola');
Insert Into country (code, country_name) Values ('AI', 'Anguilla');
Insert Into country (code, country_name) Values ('AQ', 'Antarctica');
Insert Into country (code, country_name) Values ('AG', 'Antigua & Barbuda');
Insert Into country (code, country_name) Values ('AR', 'Argentina');
Insert Into country (code, country_name) Values ('AM', 'Armenia');
Insert Into country (code, country_name) Values ('AW', 'Aruba');
Insert Into country (code, country_name) Values ('AU', 'Australia');
Insert Into country (code, country_name) Values ('AT', 'Austria');
Insert Into country (code, country_name) Values ('AZ', 'Azerbaijan');
Insert Into country (code, country_name) Values ('BS', 'Bahamas');
Insert Into country (code, country_name) Values ('BH', 'Bahrain');
Insert Into country (code, country_name) Values ('BD', 'Bangladesh');
Insert Into country (code, country_name) Values ('BB', 'Barbados');
Insert Into country (code, country_name) Values ('BY', 'Belarus');
Insert Into country (code, country_name) Values ('BE', 'Belgium');
Insert Into country (code, country_name) Values ('BZ', 'Belize');
Insert Into country (code, country_name) Values ('BJ', 'Benin');
Insert Into country (code, country_name) Values ('BM', 'Bermuda');
Insert Into country (code, country_name) Values ('BT', 'Bhutan');
Insert Into country (code, country_name) Values ('BO', 'Bolivia');
Insert Into country (code, country_name) Values ('BA', 'Bosnia & Herzegovina');
Insert Into country (code, country_name) Values ('BW', 'Botswana');
Insert Into country (code, country_name) Values ('BV', 'Bouvet Island');
Insert Into country (code, country_name) Values ('BR', 'Brazil');
Insert Into country (code, country_name) Values ('IO', 'British Indian Ocean Territory');
Insert Into country (code, country_name) Values ('VG', 'British Virgin Islands');
Insert Into country (code, country_name) Values ('BN', 'Brunei');
Insert Into country (code, country_name) Values ('BG', 'Bulgaria');
Insert Into country (code, country_name) Values ('BF', 'Burkina Faso');
Insert Into country (code, country_name) Values ('BI', 'Burundi');
Insert Into country (code, country_name) Values ('KH', 'Cambodia');
Insert Into country (code, country_name) Values ('CM', 'Cameroon');
Insert Into country (code, country_name) Values ('CA', 'Canada');
Insert Into country (code, country_name) Values ('CV', 'Cape Verde');
Insert Into country (code, country_name) Values ('BQ', 'Caribbean Netherlands');
Insert Into country (code, country_name) Values ('KY', 'Cayman Islands');
Insert Into country (code, country_name) Values ('CF', 'Central African Republic');
Insert Into country (code, country_name) Values ('TD', 'Chad');
Insert Into country (code, country_name) Values ('CL', 'Chile');
Insert Into country (code, country_name) Values ('CN', 'China');
Insert Into country (code, country_name) Values ('CX', 'Christmas Island');
Insert Into country (code, country_name) Values ('CC', 'Cocos (Keeling) Islands');
Insert Into country (code, country_name) Values ('CO', 'Colombia');
Insert Into country (code, country_name) Values ('KM', 'Comoros');
Insert Into country (code, country_name) Values ('CG', 'Congo - Brazzaville');
Insert Into country (code, country_name) Values ('CD', 'Congo - Kinshasa');
Insert Into country (code, country_name) Values ('CK', 'Cook Islands');
Insert Into country (code, country_name) Values ('CR', 'Costa Rica');
Insert Into country (code, country_name) Values ('CI', 'Côte d’Ivoire');
InSErt intO country (code, country_name) VAlUes ('hR', 'Croatia');
InSErt intO country (code, country_name) VAlUes ('cU', 'Cuba');
InSErt intO country (code, country_name) VAlUes ('cW', 'Curaçao');
INsERt into country (code, country_name) VALuEs ('cy', 'Cyprus');
INsERt into country (code, country_name) VALuEs ('cz', 'Czechia');
INsERt into country (code, country_name) VALuEs ('dk', 'Denmark');
INsERt into country (code, country_name) VALuEs ('dj', 'Djibouti');
INsERt into country (code, country_name) VALuEs ('dm', 'Dominica');
INsERt into country (code, country_name) VALuEs ('do', 'Dominican Republic');
INsERt into country (code, country_name) VALuEs ('ec', 'Ecuador');
INsERt into country (code, country_name) VALuEs ('eg', 'Egypt');
INsERt into country (code, country_name) VALuEs ('sv', 'El Salvador');
INsERt into country (code, country_name) VALuEs ('gq', 'Equatorial Guinea');
INsERt into country (code, country_name) VALuEs ('er', 'Eritrea');
INsERt into country (code, country_name) VALuEs ('ee', 'Estonia');
INsERt into country (code, country_name) VALuEs ('sz', 'Eswatini');
INsERt into country (code, country_name) VALuEs ('et', 'Ethiopia');
INsERt into country (code, country_name) VALuEs ('fk', 'Falkland Islands');
INsERt into country (code, country_name) VALuEs ('fo', 'Faroe Islands');
INsERt into country (code, country_name) VALuEs ('fj', 'Fiji');
INsERt into country (code, country_name) VALuEs ('fi', 'Finland');
INsERt into country (code, country_name) VALuEs ('fr', 'France');
INsERt into country (code, country_name) VALuEs ('gf', 'French Guiana');
INsERt into country (code, country_name) VALuEs ('pf', 'French Polynesia');
INsERt into country (code, country_name) VALuEs ('tf', 'French Southern Territories');
INsERt into country (code, country_name) VALuEs ('ga', 'Gabon');
INsERt into country (code, country_name) VALuEs ('gm', 'Gambia');
INsERt into country (code, country_name) VALuEs ('ge', 'Georgia');
INsERt into country (code, country_name) VALuEs ('de', 'Germany');
INsERt into country (code, country_name) VALuEs ('gh', 'Ghana');
INsERt into country (code, country_name) VALuEs ('gi', 'Gibraltar');
INsERt into country (code, country_name) VALuEs ('gr', 'Greece');
INsERt into country (code, country_name) VALuEs ('gl', 'Greenland');
INsERt into country (code, country_name) VALuEs ('gd', 'Grenada');
INsERt into country (code, country_name) VALuEs ('gp', 'Guadeloupe');
INsERt into country (code, country_name) VALuEs ('gu', 'Guam');
INsERt into country (code, country_name) VALuEs ('gt', 'Guatemala');
INsERt into country (code, country_name) VALuEs ('gg', 'Guernsey');
INsERt into country (code, country_name) VALuEs ('gn', 'Guinea');
INsERt into country (code, country_name) VALuEs ('gw', 'Guinea-Bissau');
INsERt into country (code, country_name) VALuEs ('gy', 'Guyana');
INsERt into country (code, country_name) VALuEs ('ht', 'Haiti');
INsERt into country (code, country_name) VALuEs ('hm', 'Heard & McDonald Islands');
INsERt into country (code, country_name) VALuEs ('hn', 'Honduras');
INsERt into country (code, country_name) VALuEs ('hk', 'Hong Kong SAR China');
INsERt into country (code, country_name) VALuEs ('hu', 'Hungary');
INsERt into country (code, country_name) VALuEs ('is', 'Iceland');
INsERt into country (code, country_name) VALuEs ('in', 'India');
INsERt into country (code, country_name) VALuEs ('id', 'Indonesia');
INsERt into country (code, country_name) VALuEs ('ir', 'Iran');
INsERt into country (code, country_name) VALuEs ('iq', 'Iraq');
INsERt into country (code, country_name) VALuEs ('ie', 'Ireland');
INsERt into country (code, country_name) VALuEs ('im', 'Isle of Man');
INsERt into country (code, country_name) VALuEs ('il', 'Israel');
INsERt into country (code, country_name) VALuEs ('it', 'Italy');
INsERt into country (code, country_name) VALuEs ('jm', 'Jamaica');
INsERt into country (code, country_name) VALuEs ('jp', 'Japan');
INsERt into country (code, country_name) VALuEs ('je', 'Jersey');
INsERt into country (code, country_name) VALuEs ('jo', 'Jordan');
INsERt into country (code, country_name) VALuEs ('kz', 'Kazakhstan');
INsERt into country (code, country_name) VALuEs ('ke', 'Kenya');
INsERt into country (code, country_name) VALuEs ('ki', 'Kiribati');
INsERt into country (code, country_name) VALuEs ('kw', 'Kuwait');
INsERt into country (code, country_name) VALuEs ('kg', 'Kyrgyzstan');
INsERt into country (code, country_name) VALuEs ('la', 'Laos');
INsERt into country (code, country_name) VALuEs ('lv', 'Latvia');
INsERt into country (code, country_name) VALuEs ('lb', 'Lebanon');
INsERt into country (code, country_name) VALuEs ('ls', 'Lesotho');
INsERt into country (code, country_name) VALuEs ('lr', 'Liberia');
INsERt into country (code, country_name) VALuEs ('ly', 'Libya');
INsERt into country (code, country_name) VALuEs ('li', 'Liechtenstein');
INsERt into country (code, country_name) VALuEs ('lt', 'Lithuania');
INsERt into country (code, country_name) VALuEs ('lu', 'Luxembourg');
INsERt into country (code, country_name) VALuEs ('mo', 'Macao SAR China');
INsERt into country (code, country_name) VALuEs ('mg', 'Madagascar');
INsERt into country (code, country_name) VALuEs ('mw', 'Malawi');
INsERt into country (code, country_name) VALuEs ('my', 'Malaysia');
INsERt into country (code, country_name) VALuEs ('mv', 'Maldives');
INsERt into country (code, country_name) VALuEs ('ml', 'Mali');
INsERt into country (code, country_name) VALuEs ('mt', 'Malta');
INsERt into country (code, country_name) VALuEs ('mh', 'Marshall Islands');
INsERt into country (code, country_name) VALuEs ('mq', 'Martinique');
INsERt into country (code, country_name) VALuEs ('mr', 'Mauritania');
INsERt into country (code, country_name) VALuEs ('mu', 'Mauritius');
INsERt into country (code, country_name) VALuEs ('yt', 'Mayotte');
INsERt into country (code, country_name) VALuEs ('mx', 'Mexico');
INsERt into country (code, country_name) VALuEs ('fm', 'Micronesia');
INsERt into country (code, country_name) VALuEs ('md', 'Moldova');
INsERt into country (code, country_name) VALuEs ('mc', 'Monaco');
INsERt into country (code, country_name) VALuEs ('mn', 'Mongolia');
INsERt into country (code, country_name) VALuEs ('me', 'Montenegro');
INsERt into country (code, country_name) VALuEs ('ms', 'Montserrat');
INsERt into country (code, country_name) VALuEs ('ma', 'Morocco');
INsERt into country (code, country_name) VALuEs ('mz', 'Mozambique');
INsERt into country (code, country_name) VALuEs ('mm', 'Myanmar (Burma)');
INsERt into country (code, country_name) VALuEs ('na', 'Namibia');
INsERt into country (code, country_name) VALuEs ('nr', 'Nauru');
INsERt into country (code, country_name) VALuEs ('np', 'Nepal');
INsERt into country (code, country_name) VALuEs ('nl', 'Netherlands');
INsERt into country (code, country_name) VALuEs ('nc', 'New Caledonia');
INsERt into country (code, country_name) VALuEs ('nz', 'New Zealand');
INsERt into country (code, country_name) VALuEs ('ni', 'Nicaragua');
INsERt into country (code, country_name) VALuEs ('ne', 'Niger');
INsERt into country (code, country_name) VALuEs ('ng', 'Nigeria');
INsERt into country (code, country_name) VALuEs ('nu', 'Niue');
INsERt into country (code, country_name) VALuEs ('nf', 'Norfolk Island');
INsERt into country (code, country_name) VALuEs ('kp', 'North Korea');
INsERt into country (code, country_name) VALuEs ('mk', 'North Macedonia');
INsERt into country (code, country_name) VALuEs ('mp', 'Northern Mariana Islands');
INsERt into country (code, country_name) VALuEs ('no', 'Norway');
INsERt into country (code, country_name) VALuEs ('om', 'Oman');
INsERt into country (code, country_name) VALuEs ('pk', 'Pakistan');
INsERt into country (code, country_name) VALuEs ('pw', 'Palau');
INsERt into country (code, country_name) VALuEs ('ps', 'Palestinian Territories');
INsERt into country (code, country_name) VALuEs ('pa', 'Panama');
INsERt into country (code, country_name) VALuEs ('pg', 'Papua New Guinea');
INsERt into country (code, country_name) VALuEs ('py', 'Paraguay');
INsERt into country (code, country_name) VALuEs ('pe', 'Peru');
INsERt into country (code, country_name) VALuEs ('ph', 'Philippines');
INsERt into country (code, country_name) VALuEs ('pn', 'Pitcairn Islands');
INsERt into country (code, country_name) VALuEs ('pl', 'Poland');
INsERt into country (code, country_name) VALuEs ('pt', 'Portugal');
INsERt into country (code, country_name) VALuEs ('pr', 'Puerto Rico');
INsERt into country (code, country_name) VALuEs ('qa', 'Qatar');
INsERt into country (code, country_name) VALuEs ('re', 'Réunion');
INSeRT into country (code, country_name) VALUeS ('ro', 'Romania');
INSeRT into country (code, country_name) VALUeS ('ru', 'Russia');
INSeRT into country (code, country_name) VALUeS ('rw', 'Rwanda');
INSeRT into country (code, country_name) VALUeS ('ws', 'Samoa');
INSeRT into country (code, country_name) VALUeS ('sm', 'San Marino');
INSeRT into country (code, country_name) VALUeS ('st', 'São Tomé & Príncipe');
INSERT INto country (code, country_name) VALUES ('sa', 'Saudi arabia');
INSERT INto country (code, country_name) VALUES ('sn', 'Senegal');
INSERT INto country (code, country_name) VALUES ('rs', 'Serbia');
INSERT INto country (code, country_name) VALUES ('sc', 'Seychelles');
INSERT INto country (code, country_name) VALUES ('sl', 'Sierra Leone');
INSERT INto country (code, country_name) VALUES ('sg', 'Singapore');
INSERT INto country (code, country_name) VALUES ('sx', 'Sint Maarten');
INSERT INto country (code, country_name) VALUES ('sk', 'Slovakia');
INSERT INto country (code, country_name) VALUES ('si', 'Slovenia');
INSERT INto country (code, country_name) VALUES ('sb', 'Solomon Islands');
INSERT INto country (code, country_name) VALUES ('so', 'Somalia');
INSERT INto country (code, country_name) VALUES ('za', 'South africa');
INSERT INto country (code, country_name) VALUES ('gs', 'South georgia & South Sandwich Islands');
INSERT INto country (code, country_name) VALUES ('kr', 'South korea');
INSERT INto country (code, country_name) VALUES ('ss', 'South sudan');
INSERT INto country (code, country_name) VALUES ('es', 'Spain');
INSERT INto country (code, country_name) VALUES ('lk', 'Sri Lanka');
INSERT INto country (code, country_name) VALUES ('bl', 'St. Barthélemy');
INSERT iNTo country (code, country_name) VALUES ('Sh', 'st. Helena');
INSERT iNTo country (code, country_name) VALUES ('Kn', 'st. Kitts & Nevis');
INSERT iNTo country (code, country_name) VALUES ('Lc', 'st. Lucia');
INSERT iNTo country (code, country_name) VALUES ('Mf', 'st. Martin');
INSERT iNTo country (code, country_name) VALUES ('Pm', 'st. Pierre & Miquelon');
INSERT iNTo country (code, country_name) VALUES ('Vc', 'st. Vincent & Grenadines');
INSERT iNTo country (code, country_name) VALUES ('Sd', 'sudan');
INSERT iNTo country (code, country_name) VALUES ('Sr', 'suriname');
INSERT iNTo country (code, country_name) VALUES ('Sj', 'svalbard & Jan Mayen');
INSERT iNTo country (code, country_name) VALUES ('Se', 'sweden');
INSERT iNTo country (code, country_name) VALUES ('Ch', 'switzerland');
INSERT iNTo country (code, country_name) VALUES ('Sy', 'syria');
INSERT iNTo country (code, country_name) VALUES ('Tw', 'taiwan');
INSERT iNTo country (code, country_name) VALUES ('Tj', 'tajikistan');
INSERT iNTo country (code, country_name) VALUES ('Tz', 'tanzania');
INSERT iNTo country (code, country_name) VALUES ('Th', 'thailand');
INSERT iNTo country (code, country_name) VALUES ('Tl', 'timor-Leste');
INSERT iNTo country (code, country_name) VALUES ('Tg', 'togo');
INSERT iNTo country (code, country_name) VALUES ('Tk', 'tokelau');
INSERT iNTo country (code, country_name) VALUES ('To', 'tonga');
INSERT iNTo country (code, country_name) VALUES ('Tt', 'trincodead & Tobago');
INSERT iNTo country (code, country_name) VALUES ('Tn', 'tunisia');
INSERT iNTo country (code, country_name) VALUES ('Tr', 'turkey');
INSERT iNTo country (code, country_name) VALUES ('Tm', 'turkmenistan');
INSERT iNTo country (code, country_name) VALUES ('Tc', 'turks & Caicos Islands');
INSERT iNTo country (code, country_name) VALUES ('Tv', 'tuvalu');
INSERT iNTo country (code, country_name) VALUES ('Um', 'u.s. Outlying Islands');
INSERT iNTo country (code, country_name) VALUES ('Vi', 'u.s. Virgin Islands');
INSERT iNTo country (code, country_name) VALUES ('Ug', 'uganda');
INSERT iNTo country (code, country_name) VALUES ('Ua', 'ukraine');
INSERT iNTo country (code, country_name) VALUES ('Ae', 'united arab Emirates');
INSERT iNTo country (code, country_name) VALUES ('Gb', 'united kingdom');
INSERT iNTo country (code, country_name) VALUES ('Us', 'united states');
INSERT iNTo country (code, country_name) VALUES ('Uy', 'uruguay');
INSERT iNTo country (code, country_name) VALUES ('Uz', 'uzbekistan');
INSERT iNTo country (code, country_name) VALUES ('Vu', 'vanuatu');
INSERT iNTo country (code, country_name) VALUES ('Va', 'vatican City');
INSERT iNTo country (code, country_name) VALUES ('Ve', 'venezuela');
INSERT iNTo country (code, country_name) VALUES ('Vn', 'vietnam');
INSERT iNTo country (code, country_name) VALUES ('Wf', 'wallis & Futuna');
INSERT iNTo country (code, country_name) VALUES ('Eh', 'western Sahara');
INSERT iNTo country (code, country_name) VALUES ('Ye', 'yemen');
INSERT iNTo country (code, country_name) VALUES ('Zm', 'zambia');
INSERT iNTo country (code, country_name) VALUES ('Zw', 'zimbabwe');